./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt
./hunyuangraph /media/jiangdie/shm_ssd/graph_10w/vas_stokes_1M.graph 2 >> test.txt